use dotenvy::dotenv;
use handlebars::Handlebars;
use inquire::{Confirm, Select, Text};
use std::{
    collections::HashMap,
    env::{args, temp_dir, var},
    fs::{copy, create_dir_all, remove_file, File, OpenOptions},
    io::{Read, Write},
    path::{absolute, Path},
    process::exit,
};

// Constants
pub const ARGS: [&str; 4] = ["help", "quick", "simple", "full"];
pub const TEMPLATES: &str =
    "https://raw.githubusercontent.com/MatteoGuadrini/psp_templates/refs/heads/main";
const LOGO: &str = "
┏━┃┏━━━━┛┏━┃
┏━┛━━━━━┃┏━┛
┛  ━━━━━┛┛";
pub const VERSION: &str = "0.7.0";
pub const SIGNATURE: &str = "Generated by psp (https://github.com/MatteoGuadrini/psp)";
pub const LOGFILE: &str = ".psp.log";
#[cfg(any(target_os = "linux", target_os = "macos"))]
pub const TOOLS: [&str; 4] = ["python3", "git", "pip3", "curl"];
#[cfg(target_os = "windows")]
pub const TOOLS: [&str; 4] = ["python.exe", "git.exe", "pip.exe", "powershell.exe"];
#[cfg(any(target_os = "linux", target_os = "macos"))]
pub const PYTHON_BIN: &str = "python3";
#[cfg(any(target_os = "linux", target_os = "macos"))]
pub const PIP_BIN: &str = "pip3";
#[cfg(any(target_os = "linux", target_os = "macos"))]
pub const SUPPORTED_PM: [&str; 2] = ["conda", "uv"];
#[cfg(any(target_os = "linux", target_os = "macos"))]
pub const SUPPORTED_BUILDER: [&str; 3] = ["hatch", "poetry", "maturin"];
#[cfg(target_family = "windows")]
pub const PYTHON_BIN: &str = "python.exe";
#[cfg(target_family = "windows")]
pub const PIP_BIN: &str = "pip.exe";
#[cfg(target_os = "windows")]
pub const SUPPORTED_PM: [&str; 2] = ["conda.exe", "uv.exe"];
#[cfg(target_os = "windows")]
pub const SUPPORTED_BUILDER: [&str; 3] = ["hatch.exe", "poetry.exe", "maturin.exe"];

// Utility functions

// Function to print in stdout the information messages
pub fn info(msg: String) {
    println!("info: {msg}");
}

// Function to print in stdout the warning messages
pub fn warning(msg: String) {
    println!("warning: {msg}");
}

// Function to print in stderr the error messages
pub fn error(msg: String) {
    eprintln!("error: {msg}");
}

// Function to split PATH environment variable
fn split_env_path() -> Vec<String> {
    let env_paths = var("PATH").ok().unwrap();
    #[cfg(any(target_os = "linux", target_os = "macos"))]
    let paths: Vec<String> = env_paths.split(':').map(String::from).collect();
    #[cfg(target_os = "windows")]
    let paths: Vec<String> = env_paths.split(';').map(String::from).collect();
    paths
}

// Function to join a path into the environment PATH variable
fn join_env_path(path: String) -> String {
    let mut paths = split_env_path();
    paths.insert(0, path);
    #[cfg(any(target_os = "linux", target_os = "macos"))]
    let separator: String = String::from(":");
    #[cfg(target_os = "windows")]
    let separator: String = String::from(";");
    paths.join(&separator)
}

// Function to check if a tool is installed
pub fn check_tool(tool: &str) -> bool {
    let paths: Vec<String> = split_env_path();
    for path in paths {
        let tool_path = Path::new(&path).join(tool);
        if Path::new(&tool_path).exists() {
            return true;
        }
    }
    false
}

// Function to create folders and parents
pub fn make_dirs(dir: &str) -> std::io::Result<()> {
    let result = create_dir_all(dir);
    if let Err(e) = result {
        error(format!("{e}"));
        exit(2);
    } else {
        Ok(())
    }
}

// Function to create a file with contents
pub fn make_file(file: &str, content: String) -> std::io::Result<()> {
    let mut file = File::create(file)?;
    let result = file.write_all(&content.as_bytes());
    if let Err(e) = result {
        error(format!("{e}"));
        exit(3);
    } else {
        Ok(())
    }
}

// Function to write the update log
pub fn write_log(log: &str, content: &str) {
    if env_psplog() {
        let mut file = OpenOptions::new()
            .append(true)
            .create(true)
            .open(log)
            .unwrap();
        writeln!(file, "{}", content).ok();
    }
}

// Function to delete the log
pub fn delete_log(log: &str) {
    if env_psplog() {
        let log_deletion = remove_file(log);
        if let Err(err) = log_deletion {
            error(format!("deletion log {log} failed; {err}"));
        }
    }
}

// Function to read the update log
pub fn read_log(log: &str) -> std::io::Result<String> {
    let mut file = File::open(log)?;
    let mut contents = String::new();
    file.read_to_string(&mut contents).ok();
    Ok(contents)
}

// Function to create Python file
pub fn create_python_file(file: &str, content: &str) -> bool {
    // Make file structures
    let py_file_ret = make_file(
        file,
        format!(
            "#! /usr/bin/env python3
# -*- encoding: utf-8 -*-
# vim: se ts=4 et syn=python:
# {SIGNATURE}, version {VERSION}

{content}"
        ),
    );
    if let Err(e) = py_file_ret {
        error(format!("{e}"));
        return false;
    }
    true
}

// Function to create Python package folder
pub fn create_python_package(path: &Path, content: &str) -> bool {
    let dir_ret = make_dirs(path.display().to_string().as_str());
    if let Err(e) = dir_ret {
        error(format!("{e}"));
        return false;
    }
    // Make file structures
    let init_file = path.join("__init__.py");
    if !create_python_file(init_file.display().to_string().as_str(), content) {
        error("`__init__.py` creation failed".to_string());
        return false;
    }
    true
}

// Function to check line into log
pub fn check_log(step: &str, log: &str) -> bool {
    let mut result = false;
    if env_psplog() && std::fs::exists(log).ok().unwrap() {
        let log_content = read_log(log);
        result = log_content.unwrap().contains(step);
    }
    result
}

// Function to get wrote values from log
pub fn get_log_value(step: &str, log: &str) -> Option<String> {
    // Find the line that starts with the step name
    log.lines()
        .find(|line| line.starts_with(step))
        .and_then(|line| {
            // Find the colon in that line
            let colon_pos = line.find(':')?;
            // Extract and trim the value after the colon
            Some(line[colon_pos + 1..].trim().to_string())
        })
}

// Function to get a Python version <MAJOR.MINOR>
pub fn get_python_version() -> String {
    let mut python = make_command(PYTHON_BIN, ".", ".", vec!["--version".to_string()], false);
    let output = python
        .output()
        .expect(format!("{PYTHON_BIN} should be installed").as_str());
    let version = std::str::from_utf8(&output.stdout)
        .unwrap()
        .replace("Python", "")
        .replace(" ", "")
        .replace("\n", "");
    format!("{}", &version[..4])
}

// Function to get file from url
pub fn get_file_from_url(url: &str, start_path: &str, output_file: &str) -> bool {
    #[cfg(any(target_os = "linux", target_os = "macos"))]
    let command = "curl";
    #[cfg(target_os = "windows")]
    let command = "powershell.exe";
    #[cfg(any(target_os = "linux", target_os = "macos"))]
    let command_args = vec![
        format!("-o{output_file}"),
        "-k".to_string(),
        "--fail".to_string(),
        "--create-dirs".to_string(),
        "--connect-timeout".to_string(),
        "10".to_string(),
        url.to_string(),
    ];
    #[cfg(target_os = "windows")]
    let command_args = vec![
        "-NoProfile".to_string(),
        "-ExecutionPolicy".to_string(),
        "Bypass".to_string(),
        "-Command".to_string(),
        "iwr".to_string(),
        "-TimeoutSec".to_string(),
        "10".to_string(),
        "-OutFile".to_string(),
        format!("( New-Item -Path '{output_file}' -Force )"),
        url.to_string(),
    ];
    let mut downloader = make_command(command, ".", start_path, command_args, false);
    let output = downloader
        .output()
        .expect(format!("{command} should be installed").as_str());
    // Check if the command exits successfully
    if !output.status.success() {
        error(format!("`{output_file}` download failed from `{url}`"));
        return false;
    }
    true
}

// Function for prompt text
pub fn prompt_text(question: &str, default: &str, help: &str) -> String {
    let answer = if help != "None" && default != "None" {
        Text::new(question)
            .with_help_message(help)
            .with_default(default)
            .prompt()
    } else if help != "None" {
        Text::new(question).with_help_message(help).prompt()
    } else if default != "None" {
        Text::new(question).with_default(default).prompt()
    } else {
        Text::new(question).prompt()
    };
    answer.unwrap().to_string()
}

// Function for prompt confirmation (yes/no)
pub fn prompt_confirm(question: &str, default: bool, help: &str) -> bool {
    let answer = if help != "None" {
        Confirm::new(question)
            .with_default(default)
            .with_help_message(help)
            .prompt()
    } else {
        Confirm::new(question).with_default(default).prompt()
    };
    answer.unwrap()
}

// Function for prompt selections
pub fn prompt_select(question: &str, options: Vec<&str>, help: &str) -> String {
    let answer = if help != "None" {
        Select::new(question, options)
            .with_help_message(help)
            .prompt()
    } else {
        Select::new(question, options).prompt()
    };
    answer.unwrap().to_string()
}

// Function to print the logo
pub fn print_logo() {
    println!("{LOGO}");
}

// Function to print help
pub fn print_help(exit_code: i32) {
    // Collect PSP_* active variables
    let mut psp_vars: Vec<String> = vec![];
    for var in dotenvy::vars() {
        if var.0.contains("PSP_") {
            psp_vars.push(var.0);
        }
    }
    print_logo();
    println!("psp (Python Scaffolding Projects), version {VERSION}");
    println!("usage: psp [shortcut]");
    println!("ie: psp [help|quick|simple|full]");
    // Print complete help
    if exit_code == 0 {
        println!(
            "
shortcut:
    help:   print this help message
    quick:  enables a rapid setup (few options included)
    simple: enables a basic setup (only Python package)
    full:   enables a full setup (all options included)

links:
    repository:     https://github.com/MatteoGuadrini/psp
    documentation:  https://psp.readthedocs.io/

templates:
    cache:  {}
    folder: {}

variables:
    {psp_vars:?}

environments:
    Python version: {}",
            env_pspcache(),
            env_psptemplatepath(),
            get_python_version()
        );
    }
    exit(exit_code)
}

// Function that captures a keyword argument
pub fn get_shortcut() -> String {
    let args: Vec<String> = args().collect();
    if args.len() > 1 {
        let shortcut = &args[1];
        if !ARGS.contains(&shortcut.as_str()) {
            error(format!("unknown shortcut command `{shortcut}`"));
            print_help(1);
        }
        shortcut.clone()
    } else {
        "None".to_string()
    }
}

// Function to get home directory
fn home_dir() -> String {
    #[cfg(any(target_os = "linux", target_os = "macos"))]
    let home_var_name = "HOME";
    #[cfg(target_os = "windows")]
    let home_var_name = "USERPROFILE";
    var(home_var_name).unwrap()
}

// Function to load env files
pub fn load_env() {
    // Load first, .env file from the current working directory
    dotenv().ok();
    // Load the second, .psp.env file from home
    let home_var = home_dir();
    let home_env = Path::new(home_var.as_str()).join(".psp.env");
    dotenvy::from_filename(home_env).ok();
}

// Function to render a template file
pub fn render_template(template: &str, file: &str, data: HashMap<&str, &str>) -> bool {
    // Create template file
    let tmp_dir = temp_dir().join("psp_templates");
    let template_path = tmp_dir.join(template).display().to_string();
    create_template(template, tmp_dir.to_str().unwrap());
    let mut handlebars = Handlebars::new();
    if let Err(e) = handlebars.register_template_file(template, &template_path) {
        error(format!("{e}; {template} is not found!"));
        return false;
    }
    let mut output_file = File::create(file).unwrap();
    // Replace variables into file
    let file_ret = handlebars.render_to_write(template, &data, &mut output_file);
    remove_file(template).ok();
    if file_ret.is_err() {
        false
    } else {
        true
    }
}

// Function to make a command
pub fn make_command(
    bin: &str,
    root: &str,
    start_path: &str,
    args: Vec<String>,
    venv: bool,
) -> std::process::Command {
    // Create start path if not exists
    let dir_ret = make_dirs(start_path);
    if let Err(e) = dir_ret {
        error(format!("start path folder creation error: {e}"));
    }
    let mut command = std::process::Command::new(bin);
    // Activate venv
    #[cfg(any(target_os = "linux", target_os = "macos"))]
    let bin_folder = "bin";
    #[cfg(target_os = "windows")]
    let bin_folder = "Scripts";
    if venv {
        command.env(
            "PATH",
            join_env_path(
                Path::new(absolute(root).unwrap().display().to_string().as_str())
                    .join(".venv")
                    .join(bin_folder)
                    .display()
                    .to_string(),
            ),
        );
    }
    command.args(&args).current_dir(start_path);
    command
}

// Function to get a project version
pub fn env_pyversion() -> String {
    // Check the version of a Python project
    let env_version = var("PSP_PYVER").ok();
    let version = if let Some(ver) = env_version {
        ver
    } else {
        "0.0.1".to_string()
    };
    version
}

// Function to get the author
pub fn env_pyauthor() -> (String, String) {
    // Check the author of a Python project
    let env_pyauthor = var("PSP_PYAUTHOR").ok();
    let pyauthor = if let Some(author) = env_pyauthor {
        author
    } else {
        "psp@python.com".to_string()
    };
    if !pyauthor.contains('@') {
        warning("`PSP_PYAUTHOR` is not a valid email".to_string());
    }
    let email = pyauthor;
    let username = email.split("@").collect::<Vec<&str>>()[0].to_string();
    (username, email)
}

// Function to get a project core builder
fn env_pybuild() -> String {
    // Check the builder
    let env_pybuild = var("PSP_PYBUILD").ok();
    let build = if let Some(b) = env_pybuild {
        b
    } else {
        "setuptools".to_string()
    };
    build
}

// Function to get update log
fn env_psplog() -> bool {
    // Check the update log
    let env_psplog = var("PSP_LOG").unwrap_or("false".to_string()).parse().ok();
    env_psplog.unwrap()
}

// Function to get template path
fn env_psptemplatepath() -> String {
    // Check the template path variable
    let env_psptemplatepath = var("PSP_TEMPLATES").ok();
    let templates = if let Some(t) = env_psptemplatepath {
        t
    } else {
        TEMPLATES.to_string()
    };
    templates
}

// Function to cache templates on local disk
pub fn env_pspcache() -> bool {
    // Check the cache variable
    let env_cache = var("PSP_CACHE").unwrap_or("false".to_string()).parse().ok();
    if env_cache.unwrap() {
        true
    } else {
        false
    }
}

// Function to check if template repository is remote url or local folder
fn check_templates_is_url(templates: &str) -> bool {
    if templates.starts_with("http") {
        return true;
    }
    false
}

// Function to create cache folder
pub fn create_cache_dir() -> String {
    let home_var = home_dir();
    let cache_dir = Path::new(home_var.as_str()).join(".psp_cache");
    if !cache_dir.exists() {
        let dir_ret = make_dirs(&cache_dir.display().to_string());
        if let Err(e) = dir_ret {
            error(format!("cache template folder creation error: {e}"));
        }
    }
    cache_dir.display().to_string()
}

// Function to download/copy template
fn create_template(template: &str, destination: &str) {
    let mut fallback: bool = true;
    let templates = env_psptemplatepath();
    let cache_template = env_pspcache();
    let template_repo = format!("{templates}/{template}");
    let destination_template = Path::new(destination).join(template);
    if templates != TEMPLATES {
        if check_templates_is_url(&template_repo) {
            // Download custom template
            if !get_file_from_url(&template_repo, destination, template) {
                fallback = true;
            }
        } else {
            // Copy custom local template
            let template_repo = Path::new(template).join(template);
            if let Err(err) = copy(&template_repo, &destination_template) {
                error(format!("copy template {template} error ({err})"));
                fallback = true;
            }
        }
    } else if cache_template {
        let cache_dir = create_cache_dir();
        let cached_template = Path::new(cache_dir.as_str()).join(template);
        if cached_template.exists() {
            if let Err(err) = copy(&cached_template, &destination_template) {
                error(format!("copy cache template {template} error ({err})"));
                fallback = true;
            }
        }
    } else {
        fallback = true;
    }
    if fallback {
        // Fallback
        get_file_from_url(template_repo.as_str(), destination, template);
    }
    // Check cache (copy to cache)
    if cache_template {
        let cache_dir = create_cache_dir();
        let cached_template = Path::new(cache_dir.as_str()).join(template);
        if !cached_template.exists() {
            if let Err(err) = copy(&destination_template, &cached_template) {
                error(format!("create cache template {template} error ({err})"));
            }
        }
    }
}

// Function to make build system settings
pub fn make_builder(root: &str, venv: bool) -> String {
    // Check environment variable for build
    let builder = env_pybuild();
    // Check if a builder is supported and installed
    if !check_builder(builder.as_str(), root, venv) {
        warning("fallback builder to `setuptools`".to_string());
    }
    let build_settings: String;
    if builder == "poetry" {
        // poetry
        build_settings = "
[build-system]
requires = ['poetry-core']
build-backend = 'poetry.core.masonry.api'"
            .to_string();
    } else if builder == "hatch" {
        // hatch
        build_settings = "
[build-system]
requires = ['hatchling']
build-backend = 'hatchling.build'"
            .to_string();
    } else if builder == "maturin" {
        // maturin
        build_settings = "
[build-system]
requires = ['maturin>=1.0,<2.0']
build-backend = 'maturin'
"
        .to_string();
    } else {
        // setuptools: defualt
        build_settings = "
[build-system]
requires = ['setuptools', 'wheel']
build-backend = 'setuptools.build_meta'"
            .to_string();
    }
    build_settings
}

// Function check another package manager
fn check_pm(pm: &str) -> bool {
    // Check if a package manager is supported
    if pm != PIP_BIN && !SUPPORTED_PM.contains(&pm) {
        error(format!("package manager `{pm}` is not supported"));
        return false;
    }
    // Check if package manager is avalaible
    if !check_tool(pm) {
        error(format!("package manager `{pm}` is not supported"));
        return false;
    }
    true
}

// Function check another builder
fn check_builder(builder: &str, root: &str, venv: bool) -> bool {
    // Check if a builder is supported
    if builder != "setuptools" && !SUPPORTED_BUILDER.contains(&builder) {
        error(format!("builder `{builder}` is not supported"));
        return false;
    }
    // Check if builder is avalaible
    if builder != "setuptools" && !check_tool(builder) {
        warning(format!("builder `{builder}` is not installed"));
        // Install builder
        let mut pip = make_pm(PIP_BIN, root, root, vec![builder.to_string()], venv);
        let output = pip
            .output()
            .expect(format!("{PIP_BIN} should be installed").as_str());
        if !output.status.success() {
            error(format!(
                "builder `{builder}` installatioon failed; use fallback"
            ));
            return false;
        }
    }
    true
}

// Function make package manager command
pub fn make_pm(
    pm: &str,
    root: &str,
    start_path: &str,
    pkgs: Vec<String>,
    venv: bool,
) -> std::process::Command {
    // Define binary for package manager
    let bin = if pm.to_lowercase() == "conda" {
        #[cfg(any(target_os = "linux", target_os = "macos"))]
        let bin = "conda";
        #[cfg(target_os = "windows")]
        let bin = "conda.exe";
        bin
    } else if pm.to_lowercase() == "uv" {
        #[cfg(any(target_os = "linux", target_os = "macos"))]
        let bin = "uv";
        #[cfg(target_os = "windows")]
        let bin = "uv.exe";
        bin
    } else {
        let bin = PIP_BIN;
        bin
    };
    // Define arguments for package manager
    let mut args: Vec<String> = vec![];
    if pm.to_lowercase() == "conda" {
        args.extend(vec!["install".to_string()]);
    } else if pm.to_lowercase() == "uv" {
        args.extend(vec!["pip".to_string(), "install".to_string()]);
    } else {
        args.extend(vec![
            "install".to_string(),
            "--timeout=10".to_string(),
            "--retries=1".to_string(),
        ]);
    }
    args.extend(pkgs.clone());
    // Check if a package manager is supported and installed
    if !check_pm(bin) {
        warning(format!("fallback package manager to `{PIP_BIN}`"));
    }
    // Make command
    make_command(bin, root, start_path, args, venv)
}
